// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4XuBY51Jo1tfaaXZ4RXcaETalxXtsGXc',
    appId: '1:453423048511:web:7394693d9e8a60689d158a',
    messagingSenderId: '453423048511',
    projectId: 'flutter-login-counter-app',
    authDomain: 'flutter-login-counter-app.firebaseapp.com',
    storageBucket: 'flutter-login-counter-app.firebasestorage.app',
    measurementId: 'G-79PY50PEYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-Yc-nGxgAGX7EteOBuJTv-10aLchkjs',
    appId: '1:453423048511:android:e76842b03d6157649d158a',
    messagingSenderId: '453423048511',
    projectId: 'flutter-login-counter-app',
    storageBucket: 'flutter-login-counter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xIAz7SBFS-jHjRyTpYwiaa12X1TdCTs',
    appId: '1:453423048511:ios:140583eb8bb7ca739d158a',
    messagingSenderId: '453423048511',
    projectId: 'flutter-login-counter-app',
    storageBucket: 'flutter-login-counter-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginCounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6xIAz7SBFS-jHjRyTpYwiaa12X1TdCTs',
    appId: '1:453423048511:ios:140583eb8bb7ca739d158a',
    messagingSenderId: '453423048511',
    projectId: 'flutter-login-counter-app',
    storageBucket: 'flutter-login-counter-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginCounterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4XuBY51Jo1tfaaXZ4RXcaETalxXtsGXc',
    appId: '1:453423048511:web:13de227baeafaaac9d158a',
    messagingSenderId: '453423048511',
    projectId: 'flutter-login-counter-app',
    authDomain: 'flutter-login-counter-app.firebaseapp.com',
    storageBucket: 'flutter-login-counter-app.firebasestorage.app',
    measurementId: 'G-QD36Y90DL3',
  );
}
